Upgrade JaCoCo Maven plug-in 0.8.7 -> 0.8.8
This version have official suport for Java 17 and 18 class files and
also have experimental support for Java 19 class files.

Previos version only officially supports Java 15 and 16 class files and
experimental support for Java 17 class files.

This should fix the errors like:

```
Error:  Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.7:report (report) on project jaguar2-api: An error has occurred in JaCoCo report generation.: Error while creating report: Error while analyzing /home/runner/work/jaguar2/jaguar2/jaguar2-api/target/classes/br/usp/each/saeg/jaguar2/spi/SpectrumExporter.class. Unsupported class file major version 62 -> [Help 1]
```

Caused by:

```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 62
	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.<init>(ClassReader.java:196)
	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.<init>(ClassReader.java:177)
	at org.jacoco.agent.rt.internal_3570298.asm.ClassReader.<init>(ClassReader.java:163)
	at org.jacoco.agent.rt.internal_3570298.core.internal.instr.InstrSupport.classReaderFor(InstrSupport.java:280)
	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:76)
	at org.jacoco.agent.rt.internal_3570298.core.instr.Instrumenter.instrument(Instrumenter.java:108)
```