XML must have exactly one root element
The previious commit (cea588f) is failing, as expected:

```
Error:  Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.0.2:validate (default) on project jaguar2-validations: While parsing /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-jacoco/target/jaguar2.xml, at file:/home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-jacoco/target/jaguar2.xml, line 1,  column 555: fatal error: The markup in the document following the root element must be well-formed.
Error:  While parsing /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-jacoco/target/jaguar2.xml, at file:/home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-jacoco/target/jaguar2.xml, line 1,  column 555: fatal error: The markup in the document following the root element must be well-formed.
Error:  While parsing /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua/target/jaguar2.xml, at file:/home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua/target/jaguar2.xml, line 1,  column 23: fatal error: Premature end of file.
Error:  While parsing /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua/target/jaguar2.xml, at file:/home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua/target/jaguar2.xml, line 1,  column 23: fatal error: Premature end of file.
```

This was made only to reproduce the error reported by #48.

Fix the issue by introducing a single root element on the exported XML.

fix #48

Also update the `requireFileChecksum` as the exporeted XML files changed
by this commit and the exported CSV file changed by cea588f.