Symblink src/main on Jaguar2 Example JUnit BA-DUA module
The validations test stated to fail on last commit (4d93c8b) because we
removed a necessary dependency of the `jaguar2-example-junit`.

The example build output is the following:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running br.usp.each.saeg.jaguar2.MaxTest
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.225 sec <<< FAILURE! - in br.usp.each.saeg.jaguar2.MaxTest
test1(br.usp.each.saeg.jaguar2.MaxTest)  Time elapsed: 0.015 sec  <<< ERROR!
java.lang.NoClassDefFoundError: br/usp/each/saeg/jaguar2/Max
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at br.usp.each.saeg.jaguar2.MaxTest.test1(MaxTest.java:22)

test2(br.usp.each.saeg.jaguar2.MaxTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: br/usp/each/saeg/jaguar2/Max
	at br.usp.each.saeg.jaguar2.MaxTest.test2(MaxTest.java:29)

test3(br.usp.each.saeg.jaguar2.MaxTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: br/usp/each/saeg/jaguar2/Max
	at br.usp.each.saeg.jaguar2.MaxTest.test3(MaxTest.java:36)

test4(br.usp.each.saeg.jaguar2.MaxTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: br/usp/each/saeg/jaguar2/Max
	at br.usp.each.saeg.jaguar2.MaxTest.test4(MaxTest.java:43)

test5(br.usp.each.saeg.jaguar2.MaxTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: br/usp/each/saeg/jaguar2/Max
	at br.usp.each.saeg.jaguar2.MaxTest.test5(MaxTest.java:50)

Results :

Tests in error:
  MaxTest.test1:22 NoClassDefFound br/usp/each/saeg/jaguar2/Max
  MaxTest.test2:29 NoClassDefFound br/usp/each/saeg/jaguar2/Max
  MaxTest.test3:36 NoClassDefFound br/usp/each/saeg/jaguar2/Max
  MaxTest.test4:43 NoClassDefFound br/usp/each/saeg/jaguar2/Max
  MaxTest.test5:50 NoClassDefFound br/usp/each/saeg/jaguar2/Max

Tests run: 5, Failures: 0, Errors: 5, Skipped: 0

Error:  There are test failures.
```

And we expect the example build output to contains following line for
validation tests succeed:

```
Tests run: 5, Failures: 1, Errors: 1, Skipped: 0
```

This is why the build is failing with the following error:

```
Error: [Verifier] File [(omitted)/jaguar2/jaguar2-validations/../jaguar2-examples/jaguar2-example-junit-ba-dua/target/surefire-reports/br.usp.each.saeg.jaguar2.MaxTest.txt] does not match regexp [Tests run: 5, Failures: 1, Errors: 1, Skipped: 0]
```

Since we removed the `jaguar2-example-junit` dependency, now we are
creating a symblink from "src/main" folder of "Jaguar2 JUnit Example"
module on "Jaguar2 Example JUnit BA-DUA" module.

I hope it will make Maven POM examples more realistic.

This should fix the build errors introduced by last commit.