Maven Wrapper using insecure endpoint to download resources
On GitHub Actions with Java 6:

```
openjdk version "1.6.0-119"
OpenJDK Runtime Environment (Zulu 6.22.0.3-linux64) (build 1.6.0-119-b119)
OpenJDK 64-Bit Server VM (Zulu 6.22.0.3-linux64) (build 23.77-b119, mixed mode)
javac 1.6.0-119
```

The build fail with the following error:

```
Error: Exception in thread "main" javax.net.ssl.SSLException: Received fatal alert: protocol_version
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1902)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1320)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1347)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1331)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:432)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1295)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:90)
	at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:76)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:72)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
Error: Process completed with exit code 1.
```

On my machine with Java 6:

```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
javac 1.6.0_65
```

The build fail with the following error:

```
Exception in thread "main" javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:882)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1188)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1215)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1199)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:476)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:166)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1195)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:234)
	at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:90)
	at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:76)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:72)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at com.sun.net.ssl.internal.ssl.InputRecord.read(InputRecord.java:462)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:863)
	... 12 more
```

As of June 18th 2018, Maven Central discontinued the support for TLSv1.1
and below and Java 6 does not support TLSv1.2.

We can't simply use HTTP protocol because, as January 15th 2020, Maven
Central no longer supports insecure communication over plain HTTP and
requires that all requests to the repository are encrypted over HTTPS.

Fortunately, we have the option of using an insecure endpoint at
http://insecure.repo1.maven.org

See:

https://blog.sonatype.com/enhancing-ssl-security-and-http/2-support-for-central
https://central.sonatype.org/articles/2018/May/04/discontinued-support-for-tlsv11-and-below
https://central.sonatype.org/faq/tls-info
https://support.sonatype.com/hc/en-us/articles/360041287334
https://blog.sonatype.com/central-repository-moving-to-https
https://central.sonatype.org/articles/2019/Nov/01/announcement-insecurerepo1mavenorg