Skip Animal Sniffer Maven Plugin when target Java 22 bytecode
Similar to commit 3b1abd6 but for Java 22 bytecode.

Otherwise the build fails with the following error:

```
Error:  Bad class file /home/runner/work/jaguar2/jaguar2/jaguar2-api/target/classes/br/usp/each/saeg/jaguar2/api/Heuristic.class
Error:  Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.23:check (default) on project jaguar2-api: Failed to check signatures: Bad class file /home/runner/work/jaguar2/jaguar2/jaguar2-api/target/classes/br/usp/each/saeg/jaguar2/api/Heuristic.class: Unsupported class file major version 66 -> [Help 1]
```