Disable Maven Javadoc Plugin `<detectOfflineLinks>` option
On Java >= 10 the Javadoc tool is reporting some errors:

```
Error:  Error fetching link: /home/runner/work/jaguar2/jaguar2/jaguar2-api/target/apidocs/package-list. Ignored it.
Error:  Error fetching link: /home/runner/work/jaguar2/jaguar2/jaguar2-core/target/apidocs/package-list. Ignored it.
Error:  Error fetching link: /home/runner/work/jaguar2/jaguar2/jaguar2-api/target/apidocs/package-list. Ignored it.
Error:  Error fetching link: /home/runner/work/jaguar2/jaguar2/jaguar2-commons/target/apidocs/package-list. Ignored it.
```

Those errors are ignored and does not affect the build status (but they
are annoying me).

Looks that the file `package-list` is not generated by Java >= 10.

See: https://stackoverflow.com/questions/49457896

Since we are targetting an old Java version I was expecting Javadoc to
generates a `package-list` file, but it dosn't.

This will probably be fixed after upgrade Maven Javadoc Plugin, but we
can't upgrade it right now.

See: commit f59d1b1134de132120252278a957593dfc9f1ef4

We could simply generate `package-list` using another tool.

See: https://github.com/networknt/javadoc-packagelist-maven-plugin

But since we are not yet publishing our Javadoc anywhere, it will create
invalid links, so maybe the best idea is to ignore those offline links.