Set source/target to 1.7 when JDK >= 12
We set default source/target to 1.6. But 1.6 is no longer supported for Java >= 12

Fix the following build error:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jaguar2-example-junit: Compilation failure: Compilation failure:
Error:  Source option 6 is no longer supported. Use 7 or later.
Error:  Target option 6 is no longer supported. Use 7 or later.
Error:  -> [Help 1]
Error:
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <goals> -rf :jaguar2-example-junit
Error: Process completed with exit code 1.
```