Upgrade JaCoCo Maven plug-in 0.8.10 -> 0.8.11
The last commit didn't break CI for Java <= 21, so let's upgrade to
version 0.8.11 that have official support for Java 21 class files and
also have experimental support for Java 22 class files.

This should fix build error when running with Java 22:

```
Error:  Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.10:report (report) on project jaguar2-api: An error has occurred in JaCoCo report generation.: Error while creating report: Error while analyzing /home/runner/work/jaguar2/jaguar2/jaguar2-api/target/classes/br/usp/each/saeg/jaguar2/CoverageControllerLoader.class with JaCoCo 0.8.10.202304240956/8ea9668. Unsupported class file major version 66
```

That cause errors on instrumentation

Caused by:

```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 66
	at org.jacoco.agent.rt.internal_4a7f17c.asm.ClassReader.<init>(ClassReader.java:199)
	at org.jacoco.agent.rt.internal_4a7f17c.asm.ClassReader.<init>(ClassReader.java:180)
	at org.jacoco.agent.rt.internal_4a7f17c.asm.ClassReader.<init>(ClassReader.java:166)
	at org.jacoco.agent.rt.internal_4a7f17c.core.internal.instr.InstrSupport.classReaderFor(InstrSupport.java:280)
	at org.jacoco.agent.rt.internal_4a7f17c.core.instr.Instrumenter.instrument(Instrumenter.java:77)
	at org.jacoco.agent.rt.internal_4a7f17c.core.instr.Instrumenter.instrument(Instrumenter.java:109)
	... 49 more
```

This is the latest version of JaCoCo. Next release will include official
support for Java 22 class files.