Upgrade JaCoCo Maven plug-in 0.8.8 -> 0.8.9
This version have official suport for Java 19 and 20 class files and
also have experimental support for Java 21 class files.

Previos version only officially supports Java 17 and 18 class files and
experimental support for Java 19 class files.

This should fix the errors like:

```
Error:  Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.8:report (report) on project jaguar2-api: An error has occurred in JaCoCo report generation.: Error while creating report: Error while analyzing /home/runner/work/jaguar2/jaguar2/jaguar2-api/target/classes/br/usp/each/saeg/jaguar2/api/IBundleSpectrum.class with JaCoCo 0.8.8.202204050719/5dcf34a. Unsupported class file major version 64
```

That also cause errors on instrumentation

Caused by:

```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 64
	at org.jacoco.agent.rt.internal_b6258fc.asm.ClassReader.<init>(ClassReader.java:199)
	at org.jacoco.agent.rt.internal_b6258fc.asm.ClassReader.<init>(ClassReader.java:180)
	at org.jacoco.agent.rt.internal_b6258fc.asm.ClassReader.<init>(ClassReader.java:166)
	at org.jacoco.agent.rt.internal_b6258fc.core.internal.instr.InstrSupport.classReaderFor(InstrSupport.java:280)
	at org.jacoco.agent.rt.internal_b6258fc.core.instr.Instrumenter.instrument(Instrumenter.java:77)
	at org.jacoco.agent.rt.internal_b6258fc.core.instr.Instrumenter.instrument(Instrumenter.java:109)
	... 49 more
```