ERRATA: Change BA-DUA Java agent file name
On PR #10 commit b1e0cdb I created Jaguar2 Example JUnit BA-DUA module.
The changes were committed with an error on purpose to show the BA-DUA
issue saeg/ba-dua#28. The error was fixed on the same PR on commit
434bcdd.

So far so good, but now I noticed that I made a mistake (It happens 💩).

Note that on commit b1e0cdb we set the `argLine` with Java agent option
pointing to a not existing file
(target/dependency/ba-dua-agent-rt-${ba-dua.version}-all.jar).

Also, note that on the fix commit 434bcdd I only updated the destination
of the downloaded BA-DUA Java agent, I didn't update the `argLine` Java
agent option to point to the existing file, because it was already
correct. Now you got my mistake, I was ahead of time ⏰.

(is really hard to use Git commit messages as documentation)

Actually, the error that I would show were the following:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: Lbr/usp/each/saeg/badua/agent/rt/internal_d2401f0/core/runtime/RuntimeData;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getField0(Class.java:2975)
	at java.lang.Class.getField(Class.java:1701)
	at br.usp.each.saeg.badua.agent.rt.internal_d2401f0.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:65)
	at br.usp.each.saeg.badua.agent.rt.internal_d2401f0.PreMain.premain(PreMain.java:25)
	... 6 more
FATAL ERROR in native method: processing of -javaagent failed
```

 I will use this commit as ERRATA for documentation, so we can use this
commit changes to validate the reported issue saeg/ba-dua#28.