git revert 4fb43e6 18b2de9
The build is failing as expected:

```
Warning:  Missing header in: /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua/src/test/java/br/usp/each/saeg/jaguar2/MaxTest.java
Warning:  Missing header in: /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4/src/test/java/br/usp/each/saeg/jaguar2/MaxTest.java
Warning:  Missing header in: /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-jacoco/src/test/java/br/usp/each/saeg/jaguar2/MaxTest.java
...
Error:  Failed to execute goal com.mycila:license-maven-plugin:2.11:check (default) on project jaguar2-parent: Some files do not have the expected license header
```

So we can revert the commit with test code changes.