Set default source/target to 1.6 on Jaguar2 Example JUnit
The version 3.1 of Apache Maven Compiler Plugin set default
source/target to 1.5. But 1.5 is no longer supported for Java >= 9

Fix the following build error:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jaguar2-example-junit: Compilation failure: Compilation failure:
Error:  Source option 1.5 is no longer supported. Use 1.6 or later.
Error:  Target option 1.5 is no longer supported. Use 1.6 or later.
Error:  -> [Help 1]
Error:
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <goals> -rf :jaguar2-example-junit
Error: Process completed with exit code 1.
```

See inception PR #1 (849bbc8, 6157727)