Jaguar2 JUnit Example using Jaguar test run listener
Configure Maven Surefire Plugin to use Jaguar2 JUnit test run listener.

Add a no-argument constructor to the test run listener, otherwise, Maven
Surefire Plugin can't instantiate the custom listener and the build will
fail with the following error:

```
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.maven.surefire.util.ReflectionUtils.instantiateOneArg(ReflectionUtils.java:130)
	at org.apache.maven.surefire.booter.SurefireReflector.instantiateProvider(SurefireReflector.java:239)
	at org.apache.maven.surefire.booter.ProviderFactory.createProvider(ProviderFactory.java:122)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:81)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.apache.maven.surefire.util.SurefireReflectionException: java.lang.InstantiationException: br.usp.each.saeg.jaguar2.junit.JaguarJUnitRunListener; nested exception is java.lang.InstantiationException: br.usp.each.saeg.jaguar2.junit.JaguarJUnitRunListener
	at org.apache.maven.surefire.util.ReflectionUtils.instantiate(ReflectionUtils.java:114)
	at org.apache.maven.surefire.common.junit4.JUnit4RunListenerFactory.createCustomListeners(JUnit4RunListenerFactory.java:43)
	at org.apache.maven.surefire.junit4.JUnit4Provider.<init>(JUnit4Provider.java:80)
	... 10 more
Caused by: java.lang.InstantiationException: br.usp.each.saeg.jaguar2.junit.JaguarJUnitRunListener
	at java.lang.Class.newInstance(Class.java:427)
	at org.apache.maven.surefire.util.ReflectionUtils.instantiate(ReflectionUtils.java:110)
	... 12 more
Caused by: java.lang.NoSuchMethodException: br.usp.each.saeg.jaguar2.junit.JaguarJUnitRunListener.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 13 more
```