Configure Apache Maven Source Plugin version
This fix two issues:

1. Removes the following warning from the build:

```
Warning:
Warning:  Some problems were encountered while building the effective model for br.usp.each.saeg:jaguar2-api:jar:0.0.1-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ br.usp.each.saeg:jaguar2-parent:0.0.1-SNAPSHOT, /home/runner/work/jaguar2/jaguar2/pom.xml, line 229, column 12
Warning:
Warning:  Some problems were encountered while building the effective model for br.usp.each.saeg:jaguar2-core:jar:0.0.1-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ br.usp.each.saeg:jaguar2-parent:0.0.1-SNAPSHOT, /home/runner/work/jaguar2/jaguar2/pom.xml, line 229, column 12
Warning:
Warning:  Some problems were encountered while building the effective model for br.usp.each.saeg:jaguar2-commons:jar:0.0.1-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ br.usp.each.saeg:jaguar2-parent:0.0.1-SNAPSHOT, /home/runner/work/jaguar2/jaguar2/pom.xml, line 229, column 12
Warning:
Warning:  Some problems were encountered while building the effective model for br.usp.each.saeg:jaguar2-junit4:jar:0.0.1-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ br.usp.each.saeg:jaguar2-parent:0.0.1-SNAPSHOT, /home/runner/work/jaguar2/jaguar2/pom.xml, line 229, column 12
Warning:
Warning:  Some problems were encountered while building the effective model for br.usp.each.saeg:jaguar2-ba-dua-provider:jar:0.0.1-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ br.usp.each.saeg:jaguar2-parent:0.0.1-SNAPSHOT, /home/runner/work/jaguar2/jaguar2/pom.xml, line 229, column 12
Warning:
Warning:  Some problems were encountered while building the effective model for br.usp.each.saeg:jaguar2-jacoco-provider:jar:0.0.1-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ br.usp.each.saeg:jaguar2-parent:0.0.1-SNAPSHOT, /home/runner/work/jaguar2/jaguar2/pom.xml, line 229, column 12
Warning:
Warning:  Some problems were encountered while building the effective model for br.usp.each.saeg:jaguar2-providers:pom:0.0.1-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ br.usp.each.saeg:jaguar2-parent:0.0.1-SNAPSHOT, /home/runner/work/jaguar2/jaguar2/pom.xml, line 229, column 12
Warning:
Warning:  Some problems were encountered while building the effective model for br.usp.each.saeg:jaguar2-csv-exporter:jar:0.0.1-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ br.usp.each.saeg:jaguar2-parent:0.0.1-SNAPSHOT, /home/runner/work/jaguar2/jaguar2/pom.xml, line 229, column 12
Warning:
Warning:  Some problems were encountered while building the effective model for br.usp.each.saeg:jaguar2-xml-exporter:jar:0.0.1-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ br.usp.each.saeg:jaguar2-parent:0.0.1-SNAPSHOT, /home/runner/work/jaguar2/jaguar2/pom.xml, line 229, column 12
Warning:
Warning:  Some problems were encountered while building the effective model for br.usp.each.saeg:jaguar2-exporters:pom:0.0.1-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ br.usp.each.saeg:jaguar2-parent:0.0.1-SNAPSHOT, /home/runner/work/jaguar2/jaguar2/pom.xml, line 229, column 12
Warning:
Warning:  Some problems were encountered while building the effective model for br.usp.each.saeg:jaguar2-validations:pom:0.0.1-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ br.usp.each.saeg:jaguar2-parent:0.0.1-SNAPSHOT, /home/runner/work/jaguar2/jaguar2/pom.xml, line 229, column 12
Warning:
Warning:  Some problems were encountered while building the effective model for br.usp.each.saeg:jaguar2-parent:pom:0.0.1-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 229, column 12
Warning:
Warning:  It is highly recommended to fix these problems because they threaten the stability of your build.
Warning:
Warning:  For this reason, future Maven versions might no longer support building such malformed projects.
Warning:
```

2. Allow build execution with Java 6 and 7.

When no version is configured the current Maven version (3.2.5) will
pick latest plug-in version (3.3.0) that is targeting Java 8 (bytecode
version 52.0). Thus, build with Java < 8 leds to the following error:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.3.0:jar-no-fork (default) on project jaguar2-parent: Execution default of goal org.apache.maven.plugins:maven-source-plugin:3.3.0:jar-no-fork failed: Unable to load the mojo 'jar-no-fork' in the plugin 'org.apache.maven.plugins:maven-source-plugin:3.3.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/apache/maven/plugins/source/SourceJarNoForkMojo : Unsupported major.minor version 52.0
```

With the following code exception:

```
Warning:  Error injecting: org.apache.maven.plugins.source.SourceJarNoForkMojo
java.lang.TypeNotPresentException: Type org.apache.maven.plugins.source.SourceJarNoForkMojo not present
	at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:115)
	at org.eclipse.sisu.space.NamedClass.load(NamedClass.java:46)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:113)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:122)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:464)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:119)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:607)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:607)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
Caused by: java.lang.UnsupportedClassVersionError: org/apache/maven/plugins/source/SourceJarNoForkMojo : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:448)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:107)
	... 48 more
```

We are still supporting build with Java 6, Using plug-in version 3.0.1.
This is the last version that can execute on Java 6.

See: https://issues.apache.org/jira/browse/MSOURCES-111
See: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12317924&version=12336941