Added `ba-dua.version` property for Jaguar2 Example JUnit BA-DUA  module
Since we are not extending the parent POM we need to include this
property, as this is not included by default anymore.

Fix the following build error:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy (default) on project jaguar2-example-junit-ba-dua: Unable to find artifact version of br.usp.each.saeg:ba-dua-agent in either dependency list or in project's dependency management. -> [Help 1]
Error:
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <goals> -rf :jaguar2-example-junit-ba-dua
Error: Process completed with exit code 1.
```