Disable BA-DUA when building with Java 22
The build for Java 22 class files is not working due to a problem with
BA-DUA. BA-DUA does not support Java 22 class files.

See: PR #35 (commit 9baef55)
See: https://github.com/saeg/ba-dua/pull/36 (commit https://github.com/saeg/ba-dua/pull/36/commits/bd71893252ad1107e641a91f92152939e26b7dcc)

The build is failing on the Jaguar2 Validations module, with the
following errors:

```
Error:  [Verifier] File not found [/home/runner/work/jaguar2/jaguar2/jaguar2-validations/../jaguar2-examples/jaguar2-example-junit4-ba-dua/target/surefire-reports/br.usp.each.saeg.jaguar2.MaxTest.txt]
Error:  [Verifier] File not found [/home/runner/work/jaguar2/jaguar2/jaguar2-validations/../jaguar2-examples/jaguar2-example-junit4-ba-dua/target/surefire-reports/br.usp.each.saeg.jaguar2.MaxTest.txt]
Error:  [Verifier] File not found [/home/runner/work/jaguar2/jaguar2/jaguar2-validations/../jaguar2-examples/jaguar2-example-junit4-ba-dua/target/surefire-reports/br.usp.each.saeg.jaguar2.MaxTest.txt]
```

Because module Jaguar2 Example JUnit4 BA-DUA is not working correctly
due to BA-DUA issue with Java 22 class files.

This is the error in the Maven output:

```
Warning:  Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua/target/surefire-reports/2024-03-20T21-58-18_092-jvmRun1.dumpstream
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
Error:  There are test failures.

Please refer to /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua && /opt/hostedtoolcache/Java_Zulu_jdk/22.0.0-36/x64/bin/java -javaagent:target/dependency/ba-dua-agent-0.8.0-runtime.jar -Doutput.file=target/badua.ser -jar /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua/target/surefire/surefirebooter3607042815661294672.jar /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua/target/surefire 2024-03-20T21-58-18_092-jvmRun1 surefire11592473037708585847tmp surefire_53078366177198809419tmp
Error occurred in starting fork, check output in log
Process Exit Code: 134
org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua && /opt/hostedtoolcache/Java_Zulu_jdk/22.0.0-36/x64/bin/java -javaagent:target/dependency/ba-dua-agent-0.8.0-runtime.jar -Doutput.file=target/badua.ser -jar /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua/target/surefire/surefirebooter3607042815661294672.jar /home/runner/work/jaguar2/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua/target/surefire 2024-03-20T21-58-18_092-jvmRun1 surefire11592473037708585847tmp surefire_53078366177198809419tmp
Error occurred in starting fork, check output in log
Process Exit Code: 134
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
```

The error is ignored due the Maven Surefire Plugin configuration.

Running in my machine I can see the Maven Surefire dump stream report:

```
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream 'FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed'.

Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream 'V  [libjvm.dylib+0x602331]  jni_FatalError+0x61'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command 'V  [libjvm.dylib+0x602331]  jni_FatalError+0x61'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:507)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:210)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:177)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:88)
	at java.base/java.lang.Thread.run(Thread.java:1570)

Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream 'V  [libjvm.dylib+0x76b6b9]  JvmtiExport::post_vm_initialized()+0x2c9'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command 'V  [libjvm.dylib+0x76b6b9]  JvmtiExport::post_vm_initialized()+0x2c9'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:507)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:210)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:177)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:88)
	at java.base/java.lang.Thread.run(Thread.java:1570)

Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream 'V  [libjvm.dylib+0xb4db7f]  Threads::create_vm(JavaVMInitArgs*, bool*)+0x69f'.

Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream 'V  [libjvm.dylib+0x620a44]  JNI_CreateJavaVM+0x64'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command 'V  [libjvm.dylib+0x620a44]  JNI_CreateJavaVM+0x64'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:507)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:210)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:177)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:88)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

And

```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
Caused by: java.lang.RuntimeException: Class java/lang/UnknownError could not be instrumented.
	at br.usp.each.saeg.badua.agent.rt.internal_2c609a4.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:67)
	at br.usp.each.saeg.badua.agent.rt.internal_2c609a4.PreMain$Init.init(PreMain.java:49)
	at br.usp.each.saeg.badua.agent.rt.internal_2c609a4.PreMain.premain(PreMain.java:31)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 3 more
Caused by: java.lang.NoSuchFieldException: DATA
	at java.base/java.lang.Class.getField(Class.java:2294)
	at br.usp.each.saeg.badua.agent.rt.internal_2c609a4.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:65)
	... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message Outstanding error when calling method in invokeJavaAgentMainMethod at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 627
*** java.lang.instrument ASSERTION FAILED ***: "success" with message invokeJavaAgentMainMethod failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 466
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 429
/bin/sh: line 1: 80150 Abort trap: 6           /Users/raraujo/Downloads/jdk/zulu22.28.91-ca-jdk22.0.0-macosx_x64/zulu-22.jdk/Contents/Home/bin/java -javaagent:target/dependency/ba-dua-agent-0.8.0-runtime.jar -Doutput.file=target/badua.ser -jar /Users/raraujo/dev/repos-saeg/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua/target/surefire/surefirebooter8844362494818513426.jar /Users/raraujo/dev/repos-saeg/jaguar2/jaguar2-examples/jaguar2-example-junit4-ba-dua/target/surefire 2024-03-20T20-07-37_796-jvmRun1 surefire8128027822039012560tmp surefire_517189331463244415045tmp
```

This commit ignores BA-DUA when running with Java 22. This can be
reverted when we upgrade BA-DUA to support Java 22 bytecode.